spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/malldb
    username: malldbuser
    password: malldbuser
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

---
com:
  yeonjidev:
    upload:
      path: upload