###
POST http://localhost:8080/api/todo/
Content-Type: application/json

{
  "title": "Sample Title",
  "writer": "user1",
  "dueDate": "2023-12-27"
}

###
PUT http://localhost:8080/api/todo/100
Content-Type: application/json

{
  "tno": 100,
  "title": "Updated Title",
  "complete": true,
  "dueDate": "2023-12-27"
}

###
DELETE http://localhost:8080/api/todo/3

###
# curl --location 'http://localhost:8080/api/products/'
#--form 'pname="Test Product"'
#--form 'pdesc="Test Product Desc"'
#--form 'files=@"/Users/yeonjinoh/Downloads/다운로드 (1).jpeg"'
POST http://localhost:8080/api/products/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="pname"

"Test Product"
--WebAppBoundary
Content-Disposition: form-data; name="pdesc"

"Test Product Desc"
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="thankyou.pdf"
Content-Type: application/pdf

< ./files/thankyou.pdf
--WebAppBoundary--

###
# curl --location 'http://localhost:8080/api/products/'
#--form 'pname="Test Product"'
#--form 'pdesc="Test Product Desc"'
#--form 'files=@"/Users/yeonjinoh/Downloads/statics_2023-08-15~2023-08-22.xlsx"'
#--form 'files=@"/Users/yeonjinoh/Downloads/thankyou.pdf"'
POST http://localhost:8080/api/products/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="pname"

"Test Product"
--WebAppBoundary
Content-Disposition: form-data; name="pdesc"

"Test Product Desc"
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="statics_2023-02-01~2023-12-07.xlsx""

< ./files/statics_2023-02-01~2023-12-07.xlsx
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="thankyou.pdf""

< ./files/thankyou.pdf
--WebAppBoundary--

###

